server:
  port: 8080
devtools:
  restart:
    enabled: true
thymeleaf:
  cache: true
  check-template: false
  
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

facebook:
  client:
    id: YOUR_FACEBOOK_CLIENT_ID
    secret: YOUR_FACEBOOK_CLIENT_SECRET
    redirect_uri: http://localhost:8080/v1/callback
    scope: public_profile
    response_type: code
  login:
    scheme: https
    host: www.facebook.com
    port: 443
    path: /v3.0/dialog/oauth
  graph-api:
    uri:
      scheme: https
      host: graph.facebook.com
      port: 443
    access-token:
      path: /v3.0/oauth/access_token
    me:
      path: /v3.0/me
      field: id,name,email