import type { GameEvent } from "@azure-voyage-rpg/engine";

/** 中央市場：第一筆交易（docs/28 第二章改編）與緋帆團初現（第六章改編）。 */
export const MARKET_EVENTS: Record<string, GameEvent> = {
  "event.market.first_trade": {
    id: "event.market.first_trade",
    precondition: { kind: "flag", flag: "flag.game_started", value: true },
    weight: 100,
    once: true,
    entryNodeId: "n1",
    nodes: [
      {
        kind: "dialogue",
        id: "n1",
        speaker: "市場掮客",
        text: "「新來的？」他打量著你，又打量著你那艘船況不佳的縱帆船，「要進貨還是出貨？」",
        goto: "check_trade",
      },
      {
        kind: "skillCheck",
        id: "check_trade",
        stat: "trade",
        difficulty: 15,
        onSuccess: "n_win",
        onFailure: "n_ok",
      },
      {
        kind: "dialogue",
        id: "n_win",
        speaker: "旁白",
        text: "你精準地看穿了對方的報價空間，用低於市價的成本，換到了一船划算的橄欖油。",
        goto: "n_close",
      },
      {
        kind: "dialogue",
        id: "n_ok",
        speaker: "旁白",
        text: "你花了比預期多一點的價錢，但貨到底是進了船艙。帳本上第一筆墨跡，還是落下了。",
        goto: "n_close",
      },
      {
        kind: "effect",
        id: "n_close",
        effect: { setFlags: ["flag.first_trade_done"], advanceTime: 1 },
        goto: "n_end",
      },
      {
        kind: "dialogue",
        id: "n_end",
        speaker: "旁白",
        text: "碼頭的掮客多看了你的船兩眼，壓低聲音議論——「新來的。撐得過這季風暴嗎？」",
        goto: "END",
      },
    ],
  },
  "event.market.bulk_contract": {
    id: "event.market.bulk_contract",
    precondition: {
      kind: "and",
      all: [
        { kind: "flag", flag: "flag.first_trade_done", value: true },
        { kind: "flag", flag: "flag.crew_assembled", value: true },
      ],
    },
    weight: 70,
    once: false,
    cooldownDays: 1,
    entryNodeId: "n1",
    nodes: [
      {
        kind: "dialogue",
        id: "n1",
        speaker: "市場掮客",
        text: "「來得正好，」掮客把一張急單推過來，「兩批補給今晚就要出港。你要接穩單，還是賭高價那批？」",
        goto: "n2",
      },
      {
        kind: "choice",
        id: "n2",
        prompt: "你要怎麼接這份急單？",
        options: [
          { label: "接穩定補給線，利潤薄但風險低", goto: "n_safe_effect" },
          { label: "吃下高價風險單，試著賺一筆大的", goto: "check_trade" },
        ],
      },
      {
        kind: "effect",
        id: "n_safe_effect",
        effect: {
          setFlags: ["flag.supply_contract_signed"],
          reputation: [{ area: "area.aurelia", delta: 3 }],
          worldState: [{ path: "crimsonThreat", delta: -1 }],
          advanceTime: 1,
        },
        goto: "n_safe_close",
      },
      {
        kind: "dialogue",
        id: "n_safe_close",
        speaker: "賽菈",
        text: "「錢少一點，但帳面很乾淨，」賽菈點頭，「我們先把航線跑穩，商會才站得住。」",
        goto: "END",
      },
      {
        kind: "skillCheck",
        id: "check_trade",
        stat: "trade",
        difficulty: 26,
        onSuccess: "n_risk_win",
        onFailure: "n_risk_fail",
      },
      {
        kind: "dialogue",
        id: "n_risk_win",
        speaker: "旁白",
        text: "你在最後一刻談下有利條款，貨單價格被你抬高了一截，港邊商販對晨汐商會另眼相看。",
        goto: "n_risk_win_effect",
      },
      {
        kind: "effect",
        id: "n_risk_win_effect",
        effect: {
          setFlags: ["flag.supply_contract_signed"],
          reputation: [{ area: "area.aurelia", delta: 4 }],
          worldState: [{ path: "crimsonThreat", delta: 1 }],
          advanceTime: 1,
        },
        goto: "END",
      },
      {
        kind: "dialogue",
        id: "n_risk_fail",
        speaker: "旁白",
        text: "你沒能壓住對方條件，高價單的保費和延誤罰金反咬一口。這趟不至於致命，卻讓你記得貪快的代價。",
        goto: "n_risk_fail_effect",
      },
      {
        kind: "effect",
        id: "n_risk_fail_effect",
        effect: {
          setFlags: ["flag.supply_contract_signed"],
          worldState: [{ path: "crimsonThreat", delta: 2 }],
          advanceTime: 1,
        },
        goto: "END",
      },
    ],
  },
  "event.market.crimson_scout": {
    id: "event.market.crimson_scout",
    precondition: {
      kind: "and",
      all: [
        { kind: "flag", flag: "flag.crew_assembled", value: true },
        { kind: "not", cond: { kind: "flag", flag: "flag.first_battle_done", value: true } },
      ],
    },
    weight: 100,
    once: true,
    entryNodeId: "n1",
    nodes: [
      {
        kind: "dialogue",
        id: "n1",
        speaker: "旁白",
        text: "碼頭瞭望台傳來示警的鐘聲——一艘掛著緋紅船帆的武裝快船，正朝著晨汐商會的方向撲來。",
        goto: "n2",
      },
      {
        kind: "choice",
        id: "n2",
        prompt: "布拉姆看著你，等你下令。",
        options: [
          { label: "迎上去，正面周旋", goto: "check_combat" },
          { label: "把船逼進淺水暗礁區，甩開他們", goto: "check_nav" },
        ],
      },
      {
        kind: "skillCheck",
        id: "check_combat",
        stat: "combat",
        difficulty: 25,
        onSuccess: "n_win",
        onFailure: "n_scar",
      },
      {
        kind: "skillCheck",
        id: "check_nav",
        stat: "nav",
        difficulty: 20,
        onSuccess: "n_win",
        onFailure: "n_scar",
      },
      {
        kind: "dialogue",
        id: "n_win",
        speaker: "旁白",
        text: "砲聲停下的時候，甲板上瀰漫著硝煙與海水的氣味。緋帆快船掛著兩道焦痕，不甘地掉頭撤退。",
        goto: "n_effect_win",
      },
      {
        kind: "dialogue",
        id: "n_scar",
        speaker: "旁白",
        text: "海燕號的主帆又裂開了一道口子，但船還浮著，人一個沒少——這是不體面、卻活下來的一仗。",
        goto: "n_effect_scar",
      },
      {
        kind: "effect",
        id: "n_effect_win",
        effect: {
          setFlags: ["flag.first_battle_done", "flag.first_battle_won"],
          worldState: [{ path: "crimsonThreat", delta: 10 }],
          unlock: { areas: ["area.perlan"], scenes: ["scene.perlan.docks"] },
        },
        goto: "n_end",
      },
      {
        kind: "effect",
        id: "n_effect_scar",
        effect: {
          setFlags: ["flag.first_battle_done", "flag.first_battle_fled"],
          worldState: [{ path: "crimsonThreat", delta: 10 }],
          unlock: { areas: ["area.perlan"], scenes: ["scene.perlan.docks"] },
        },
        goto: "n_end",
      },
      {
        kind: "dialogue",
        id: "n_end",
        speaker: "布拉姆",
        text: "「有個人站在船尾一直看著我們，」他抹了把臉上的硝煙，「像在記你的臉。」",
        goto: "END",
      },
    ],
  },
};
