-- AlterTable
ALTER TABLE "Guild" ADD COLUMN     "captainCombat" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "captainExp" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "captainLead" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "captainLore" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "captainNav" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "captainTrade" INTEGER NOT NULL DEFAULT 20;
